ingress-nginx:
  controller:
    publishService:
      enabled: true

kafka:
  kraft:
    enabled: false
  zookeeper:
    enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
  replicaCount: 2

redis:
  auth:
    enabled: false

consumer:
  deployment:
    name: consumer-deployment
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    containers:
      image: registry.gitlab.com/somszabolcs3/uhubprojekt/consumer:latest
      imagePullPolicy: Always
      ports:
        containerPort: 3000
        protocol: TCP
    imagePullSecrets:
        name: registry-demo-secret
  service:
    ports:
      port: 3000
    type: ClusterIP

database:
  deployment:
    replicas: 3
    terminationGracePeriodSeconds: 10
    env:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: logs

lister:
  deployment:
    name: lister-deployment
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    containers:
      image: registry.gitlab.com/somszabolcs3/uhubprojekt/lister:latest
      imagePullPolicy: Always
      ports:
        containerPort: 3000
        protocol: TCP
    imagePullSecrets:
        name: registry-demo-secret
  service:
    ports:
      port: 3000
    type: ClusterIP

lister2:
  deployment:
    name: lister2-deployment
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    containers:
      image: registry.gitlab.com/somszabolcs3/uhubprojekt/lister2:latest
      imagePullPolicy: Always
      ports:
        containerPort: 3000
        protocol: TCP
    imagePullSecrets:
        name: registry-demo-secret
  service:
    ports:
      port: 3000
    type: ClusterIP

producer:
  deployment:
    name: producer-deployment
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    containers:
      image: registry.gitlab.com/somszabolcs3/uhubprojekt/producer:latest
      imagePullPolicy: Always
      ports:
        containerPort: 3000
        protocol: TCP
    imagePullSecrets:
        name: registry-demo-secret
  service:
    ports:
      port: 3000
    type: ClusterIP