apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2l0bGFiLWNpLXRva2VuIiwicGFzc3dvcmQiOiJnbHBhdC01V1pzVE1oeVNqWmQ5VlZpOW9SeCIsImF1dGgiOiJaMmwwYkdGaUxXTnBMWFJ2YTJWdU9tZHNjR0YwTFRWWFduTlVUV2g1VTJwYVpEbFdWbWs1YjFKNCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-demo-secret
type: kubernetes.io/dockerconfigjson
